# Generated by Django 4.2.6 on 2023-11-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('dob', models.CharField(max_length=50)),
                ('selectMembershipPlan', models.CharField(max_length=200)),
                ('selectTrainer', models.CharField(max_length=55)),
                ('reference', models.CharField(max_length=55)),
                ('address', models.TextField()),
                ('paymentStatus', models.CharField(blank=True, max_length=55, null=True)),
                ('price', models.IntegerField(blank=True, max_length=55, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=185)),
                ('price', models.IntegerField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('gender', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('salary', models.IntegerField(max_length=25)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
