# Generated by Django 4.2.6 on 2023-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_date', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=100)),
                ('logout', models.CharField(max_length=100)),
                ('select_workout', models.CharField(max_length=100)),
                ('trainer_by', models.CharField(max_length=100)),
            ],
        ),
    ]
