# Generated by Django 4.2.6 on 2023-11-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
