# Generated by Django 4.2.6 on 2023-11-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_attendence_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='login',
            new_name='deslogar',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='logout',
            new_name='logar',
        ),
    ]
